input("Nama : ")
print("Salsabila Syifa")
input("NIM : ")
input("Kelas Paralel : ")
input("Tempat/Tanggal Lahir : ")
print("Banjarmasin/06-02-2002")
input("Alamat : ")
input("Hobby : ")
input("No. HP : ")